### ISSUE TITLE
Feature request: Allow NSTokenField to automatically expand vertically to fit tokens.

### ISSUE THREAD

**Issue by oisinlavery** [akhilcb/ACBTokenField#1]

**Comment by akhilcb** [comment]
Thanks for trying it out. I will look into this when I get some time. PR is also welcome.

**Comment by akhilcb** [comment]
I am not sure if everyone would prefer this hence I am not planning to include this for now. But if anyone is interested, here is the solution:

https://stackoverflow.com/questions/17147366/auto-resizing-nstokenfield-with-constraint-based-layout
